repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: python
        files: '.*\.py'
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        files: '.*\.py'
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
