version: '2.4'

services:
 app:
    build:
      context: ./
    restart: on-failure:5
    container_name: vigilant-crypto-snatch
    command: vigilant_crypto_snatch.py --marketplace=kraken
    security_opt:
      - apparmor:docker-default
      - no-new-privileges
    volumes:
      - ./config:/root/.config:ro
      # Use the same time zone as the host machine.
      - /etc/localtime:/etc/localtime:ro
