site_name: Vigilant Crypto Snatch
site_url: 'https://martin-ueding.github.io/vigilant-crypto-snatch/'

theme:
  name: material

nav:
  - index.md
  - installation.md
  - configuration.md
  - running.md
  - support.md
  - changelog.md
  - developing.md
  - license.md
  - donation.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
