site_name: Vigilant Crypto Snatch
site_url: 'https://martin-ueding.github.io/vigilant-crypto-snatch/'

theme:
  name: material

nav:
  - index.md
  - installation.md
  - configuration.md
  - running.md
  - deployment.md
  - support.md
  - Changelog:
    - changelog/version-2.md
    - changelog/version-3.md
    - changelog/version-4.md
    - changelog/version-5.md
  - Development:
    - developing.md
    - dev/components.md
  - license.md
  - donation.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
