site_name: Vigilant Crypto Snatch

theme:
  name: material

nav:
  - index.md
  - configuration.md
  - running.md
  - developing.md
  - license.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences