site_name: Vigilant Crypto Snatch
site_url: 'https://martin-ueding.github.io/vigilant-crypto-snatch/'

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

nav:
  - index.md
  - installation.md
  - Configuration:
    - configuration/general.md
    - configuration/marketplace.md
    - configuration/triggers.md
  - Usage:
    - usage/general.md
    - usage/test-drive.md
    - usage/watch.md
    - usage/evaluate.md
  - deployment.md
  - support.md
  - Changelog:
    - changelog/version-2.md
    - changelog/version-3.md
    - changelog/version-4.md
    - changelog/version-5.md
  - Development:
    - developing.md
    - dev/components.md
  - license.md
  - donation.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
