[tool.poetry]
name = "vigilant-crypto-snatch"
version = "1.0.0"
description = ""
authors = ["Martin Ueding <mu@martin-ueding.de>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
sqlalchemy = "^1.3.23"
pyyaml = "^5.4.1"
clikraken = "^0.8.3"
BitstampClient = "^2.2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
