# Sample configuration file. Copy this and the main script into
# `~/.config/vigilant-crypto-snatch.yml` and customize it.

# For the trading on Bitstamp.net you need to create an API key which has the
# necessary permissions. Enter the details here.
bitstamp:
  username: 'username here'
  key: 'key here'
  secret: 'secret here'

# Get you free API key from
# [Cryptocompare](https://min-api.cryptocompare.com/pricing) to retrieve
# historical BTC/EUR prices as long as they are not yet fetched via the
# Bitstamp API calls.
cryptocompare:
  api_key: 'your API key here'

# Telegram API:
# create your telegram bot like in this tutorial: https://www.christian-luetgens.de/homematic/telegram/botfather/Chat-Bot.htm
# insert your bot details below:
telegram:
  token: 'Your bot token here'
  chat_id: 'Your chat ID here'

# The minutes interval to wait between checks of the COIN/FIAT prices. For testing
# this can be rather short, for production a minute likely is plenty frequent.
sleep: 60

# Trigger config: minutes in minutes, drop in percent, amount to buy in FIAT. Be
# aware that more than one trigger can be triggered during one price update and
# adjust your invested money accordingly. Create as many triggers as you want usung the same schematic as below. 
# Use Point (.) to write drops like 4.5% not comma (,).
# Be aware that if you run this for the very first time and a trigger meets the condition, it will be executed 
# immidiatly! The simple DCA trigger below will also trigger no matter what. 
# Use # in front of a trigger to disable it.

triggers:
  - { minutes: 60, drop: 5, eur: 30 }
   
  - { minutes: 240, drop: 5, eur: 30 }

# If you get nonce errors on kraken consider using less triggers or modify the nonce: https://support.kraken.com/hc/en-us/articles/360001148063-Why-am-I-getting-Invalid-Nonce-Errors-

  
# To implement a simple DCA stragety apart from the buys during drops you can modify a trigger like this:

  - { minutes: 11720, drop: 0.0001, eur: 300 }
  
# In this case the trigger will be fired every 7 days and makes a market buy no matter where the price is for 300 fiatunits.


# Choose your currency pairs you want the skipt to run on. You can choose as many as you want but be carefull, the triggers are the same for all pairs!!!

currency_pairs:
  - ['BTC', 'EUR']
#  - ['crypto', 'FIAT']
