# Sample configuration file. Copy this and the main script into
# `~/.config/vigilant-crypto-snatch.yml` and customize it.

# For the trading on Bitstamp.net you need to create an API key which has the
# necessary permissions. Enter the details here.
bitstamp:
  username: 'username here'
  key: 'key here'
  secret: 'secret here'

# Get you free API key from
# [Cryptocompare](https://min-api.cryptocompare.com/pricing) to retrieve
# historical BTC/EUR prices as long as they are not yet fetched via the
# Bitstamp API calls.
cryptocompare:
  api_key: 'your API key here'
  
  
## Telegram API:
## create your telegram bot like in this tutorial: https://www.christian-luetgens.de/homematic/telegram/botfather/Chat-Bot.htm
## insert your bot details below:

##!!!!!!This is not functional yet!!!!!!!!

telegram:
  bot_chat: 'Your ChatID here'
  bot_http: 'Your Bot token here'

# The minutes interval to wait between checks of the BTC/EUR prices. For testing
# this can be rather short, for production a minute likely is plenty frequent.
sleep: 60

# Trigger config: minutes in minutes, drop in percent, amount to buy in EUR. Be
# aware that more than one trigger can be triggered during one price update and
# adjust your invested money accordingly. Use Point (.) to write drops like 4.5% not comma (,).
triggers:
  - { minutes: 60, drop: 5, eur: 30 }
  - { minutes: 60, drop: 10, eur: 50 }
  - { minutes: 60, drop: 15, eur: 70 }
  - { minutes: 60, drop: 20, eur: 90 }
  - { minutes: 60, drop: 25, eur: 100 }
  - { minutes: 60, drop: 30, eur: 70 }
  - { minutes: 60, drop: 35, eur: 70 }   

  - { minutes: 240, drop: 5, eur: 30 }
  - { minutes: 240, drop: 10, eur: 50 }
  - { minutes: 240, drop: 15, eur: 70 }
  - { minutes: 240, drop: 20, eur: 90 }
  - { minutes: 240, drop: 25, eur: 100 }
  - { minutes: 240, drop: 30, eur: 70 }

